"""add_intransit_to_sap_stock

Revision ID: 3a7b06ef4865
Revises: bf54eac36739
Create Date: 2026-05-12 15:57:41.774202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a7b06ef4865'
down_revision: Union[str, Sequence[str], None] = 'bf54eac36739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sap_stock', sa.Column('intransit', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sap_stock', 'intransit')
    # ### end Alembic commands ###
