"""warehouse_master_final

Revision ID: 9124c1bb0614
Revises: 3a7b06ef4865
Create Date: 2026-05-15 11:29:15.857217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9124c1bb0614'
down_revision: Union[str, Sequence[str], None] = '3a7b06ef4865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE FROM stock_calculations')
    op.execute('DELETE FROM photos')
    op.execute('DELETE FROM area_grouping')
    
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_gudang', sa.String(length=200), nullable=True),
    sa.Column('kota', sa.String(length=100), nullable=True),
    sa.Column('kode_kab', sa.Integer(), nullable=True),
    sa.Column('provinsi', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    op.create_index(op.f('ix_warehouses_kode_kab'), 'warehouses', ['kode_kab'], unique=False)
    op.create_index(op.f('ix_warehouses_nama_gudang'), 'warehouses', ['nama_gudang'], unique=False)
    op.create_table('warehouse_plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gudang_id', sa.Integer(), nullable=False),
    sa.Column('kode_plant', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['gudang_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_plants_gudang_id'), 'warehouse_plants', ['gudang_id'], unique=False)
    op.create_index(op.f('ix_warehouse_plants_id'), 'warehouse_plants', ['id'], unique=False)
    op.create_index(op.f('ix_warehouse_plants_kode_plant'), 'warehouse_plants', ['kode_plant'], unique=True)
    op.drop_index(op.f('ix_master_plant_kode_plant'), table_name='master_plant')
    op.drop_table('master_plant')
    op.add_column('area_grouping', sa.Column('gudang_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_area_grouping_gudang_id'), 'area_grouping', ['gudang_id'], unique=False)
    op.create_unique_constraint('uq_area_grouping_kab_gudang', 'area_grouping', ['kode_kab', 'gudang_id'])
    op.create_foreign_key(None, 'area_grouping', 'warehouses', ['gudang_id'], ['id'])
    op.drop_column('area_grouping', 'kode_plant')
    op.add_column('photos', sa.Column('gudang_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_photos_gudang_id'), 'photos', ['gudang_id'], unique=False)
    op.create_index('ix_photos_tanggal_gudang', 'photos', ['tanggal', 'gudang_id'], unique=False)
    op.create_foreign_key(None, 'photos', 'warehouses', ['gudang_id'], ['id'])
    op.drop_column('photos', 'kode_plant2')
    op.drop_column('photos', 'kode_plant')
    op.add_column('stock_calculations', sa.Column('gudang_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_stock_calculations_gudang_id'), 'stock_calculations', ['gudang_id'], unique=False)
    op.create_unique_constraint('uq_stock_calc_tanggal_gudang_tipe', 'stock_calculations', ['tanggal', 'gudang_id', 'tipe_pupuk'])
    op.create_foreign_key(None, 'stock_calculations', 'warehouses', ['gudang_id'], ['id'])
    op.drop_column('stock_calculations', 'kode_plant')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_calculations', sa.Column('kode_plant', mysql.VARCHAR(length=10), nullable=False))
    op.drop_constraint(None, 'stock_calculations', type_='foreignkey')
    op.drop_constraint('uq_stock_calc_tanggal_gudang_tipe', 'stock_calculations', type_='unique')
    op.drop_index(op.f('ix_stock_calculations_gudang_id'), table_name='stock_calculations')
    op.drop_column('stock_calculations', 'gudang_id')
    op.add_column('photos', sa.Column('kode_plant', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('photos', sa.Column('kode_plant2', mysql.VARCHAR(length=10), nullable=True))
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.drop_index('ix_photos_tanggal_gudang', table_name='photos')
    op.drop_index(op.f('ix_photos_gudang_id'), table_name='photos')
    op.drop_column('photos', 'gudang_id')
    op.add_column('area_grouping', sa.Column('kode_plant', mysql.VARCHAR(length=10), nullable=False))
    op.drop_constraint(None, 'area_grouping', type_='foreignkey')
    op.drop_constraint('uq_area_grouping_kab_gudang', 'area_grouping', type_='unique')
    op.drop_index(op.f('ix_area_grouping_gudang_id'), table_name='area_grouping')
    op.drop_column('area_grouping', 'gudang_id')
    op.create_table('master_plant',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('kode_plant', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('nama_gudang', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('anper', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('lini', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('kabupaten', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('kode_kab', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('provinsi', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('kapasitas_ton', mysql.FLOAT(), nullable=True),
    sa.Column('has_cctv', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('sharing_kode_plant', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_master_plant_kode_plant'), 'master_plant', ['kode_plant'], unique=True)
    op.drop_index(op.f('ix_warehouse_plants_kode_plant'), table_name='warehouse_plants')
    op.drop_index(op.f('ix_warehouse_plants_id'), table_name='warehouse_plants')
    op.drop_index(op.f('ix_warehouse_plants_gudang_id'), table_name='warehouse_plants')
    op.drop_table('warehouse_plants')
    op.drop_index(op.f('ix_warehouses_nama_gudang'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_kode_kab'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.drop_table('warehouses')
    # ### end Alembic commands ###
