"""add_sap_uploads

Revision ID: bf54eac36739
Revises: 
Create Date: 2026-05-12 11:38:24.115644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf54eac36739'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_plant', sa.String(length=10), nullable=False),
    sa.Column('nama_gudang', sa.String(length=200), nullable=True),
    sa.Column('anper', sa.String(length=10), nullable=True),
    sa.Column('lini', sa.String(length=20), nullable=True),
    sa.Column('kabupaten', sa.String(length=100), nullable=True),
    sa.Column('kode_kab', sa.Integer(), nullable=True),
    sa.Column('provinsi', sa.String(length=100), nullable=True),
    sa.Column('kapasitas_ton', sa.Float(), nullable=True),
    sa.Column('has_cctv', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sharing_kode_plant', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_plant_id'), 'master_plant', ['id'], unique=False)
    op.create_index(op.f('ix_master_plant_kode_kab'), 'master_plant', ['kode_kab'], unique=False)
    op.create_index(op.f('ix_master_plant_kode_plant'), 'master_plant', ['kode_plant'], unique=True)
    op.create_table('notification_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('kode_kab', sa.Integer(), nullable=False),
    sa.Column('kabupaten', sa.String(length=100), nullable=True),
    sa.Column('provinsi', sa.String(length=100), nullable=True),
    sa.Column('jenis_pupuk', sa.String(length=20), nullable=True),
    sa.Column('stok_tersedia', sa.Float(), nullable=True),
    sa.Column('safety_stock', sa.Float(), nullable=True),
    sa.Column('pct_of_ss', sa.Float(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fcm_success', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_log_id'), 'notification_log', ['id'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('kode_plant', sa.String(length=10), nullable=False),
    sa.Column('kode_plant2', sa.String(length=10), nullable=True),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('r2_key', sa.String(length=300), nullable=False),
    sa.Column('r2_url', sa.Text(), nullable=False),
    sa.Column('feed_number', sa.Integer(), nullable=False),
    sa.Column('file_size_kb', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_id'), 'photos', ['id'], unique=False)
    op.create_index(op.f('ix_photos_kode_plant'), 'photos', ['kode_plant'], unique=False)
    op.create_index(op.f('ix_photos_tanggal'), 'photos', ['tanggal'], unique=False)
    op.create_index('ix_photos_tanggal_plant', 'photos', ['tanggal', 'kode_plant'], unique=False)
    op.create_table('safety_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_kab', sa.Integer(), nullable=False),
    sa.Column('kabupaten', sa.String(length=100), nullable=True),
    sa.Column('provinsi', sa.String(length=100), nullable=True),
    sa.Column('ss_urea', sa.Float(), nullable=True),
    sa.Column('ss_npk', sa.Float(), nullable=True),
    sa.Column('ss_npk_kakao', sa.Float(), nullable=True),
    sa.Column('ss_za', sa.Float(), nullable=True),
    sa.Column('ss_sp36', sa.Float(), nullable=True),
    sa.Column('ss_organik', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_stock_id'), 'safety_stock', ['id'], unique=False)
    op.create_index(op.f('ix_safety_stock_kode_kab'), 'safety_stock', ['kode_kab'], unique=True)
    op.create_table('sap_outstanding_do',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('kode_plant', sa.String(length=10), nullable=False),
    sa.Column('jenis_pupuk', sa.String(length=20), nullable=False),
    sa.Column('nomor_so', sa.String(length=30), nullable=True),
    sa.Column('outstanding_qty', sa.Float(), nullable=True),
    sa.Column('status_so', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sap_do_tanggal_plant_jenis', 'sap_outstanding_do', ['tanggal', 'kode_plant', 'jenis_pupuk'], unique=False)
    op.create_index(op.f('ix_sap_outstanding_do_id'), 'sap_outstanding_do', ['id'], unique=False)
    op.create_index(op.f('ix_sap_outstanding_do_kode_plant'), 'sap_outstanding_do', ['kode_plant'], unique=False)
    op.create_index(op.f('ix_sap_outstanding_do_tanggal'), 'sap_outstanding_do', ['tanggal'], unique=False)
    op.create_table('sap_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('kode_plant', sa.String(length=10), nullable=False),
    sa.Column('jenis_pupuk', sa.String(length=20), nullable=False),
    sa.Column('material_code', sa.String(length=20), nullable=True),
    sa.Column('material_desc', sa.String(length=200), nullable=True),
    sa.Column('storage_location', sa.String(length=10), nullable=True),
    sa.Column('unrestricted', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sap_stock_id'), 'sap_stock', ['id'], unique=False)
    op.create_index(op.f('ix_sap_stock_kode_plant'), 'sap_stock', ['kode_plant'], unique=False)
    op.create_index(op.f('ix_sap_stock_tanggal'), 'sap_stock', ['tanggal'], unique=False)
    op.create_index('ix_sap_stock_tanggal_plant_jenis', 'sap_stock', ['tanggal', 'kode_plant', 'jenis_pupuk'], unique=False)
    op.create_table('stock_calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('kode_plant', sa.String(length=10), nullable=False),
    sa.Column('tipe_pupuk', sa.String(length=20), nullable=False),
    sa.Column('stok_fisik', sa.Float(), nullable=True),
    sa.Column('outstanding_so', sa.Float(), nullable=True),
    sa.Column('stok_admin_tanpa_intransit', sa.Float(), nullable=True),
    sa.Column('intransit', sa.Float(), nullable=True),
    sa.Column('stok_admin', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tanggal', 'kode_plant', 'tipe_pupuk', name='uq_stock_calc_tanggal_plant_tipe')
    )
    op.create_index(op.f('ix_stock_calculations_id'), 'stock_calculations', ['id'], unique=False)
    op.create_index(op.f('ix_stock_calculations_kode_plant'), 'stock_calculations', ['kode_plant'], unique=False)
    op.create_index(op.f('ix_stock_calculations_tanggal'), 'stock_calculations', ['tanggal'], unique=False)
    op.create_index(op.f('ix_stock_calculations_tipe_pupuk'), 'stock_calculations', ['tipe_pupuk'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('hashed_pw', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('area_grouping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_kab', sa.Integer(), nullable=False),
    sa.Column('kabupaten', sa.String(length=100), nullable=True),
    sa.Column('provinsi', sa.String(length=100), nullable=True),
    sa.Column('kode_plant', sa.String(length=10), nullable=False),
    sa.Column('is_configured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['kode_plant'], ['master_plant.kode_plant'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode_kab', 'kode_plant', name='uq_area_grouping_kab_plant')
    )
    op.create_index(op.f('ix_area_grouping_id'), 'area_grouping', ['id'], unique=False)
    op.create_index(op.f('ix_area_grouping_kode_kab'), 'area_grouping', ['kode_kab'], unique=False)
    op.create_index(op.f('ix_area_grouping_kode_plant'), 'area_grouping', ['kode_plant'], unique=False)
    op.create_table('fcm_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('device_info', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fcm_tokens_id'), 'fcm_tokens', ['id'], unique=False)
    op.create_table('sap_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jenis_file', sa.String(length=20), nullable=False),
    sa.Column('tanggal_data', sa.Date(), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('jumlah_baris', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sap_uploads_id'), 'sap_uploads', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sap_uploads_id'), table_name='sap_uploads')
    op.drop_table('sap_uploads')
    op.drop_index(op.f('ix_fcm_tokens_id'), table_name='fcm_tokens')
    op.drop_table('fcm_tokens')
    op.drop_index(op.f('ix_area_grouping_kode_plant'), table_name='area_grouping')
    op.drop_index(op.f('ix_area_grouping_kode_kab'), table_name='area_grouping')
    op.drop_index(op.f('ix_area_grouping_id'), table_name='area_grouping')
    op.drop_table('area_grouping')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stock_calculations_tipe_pupuk'), table_name='stock_calculations')
    op.drop_index(op.f('ix_stock_calculations_tanggal'), table_name='stock_calculations')
    op.drop_index(op.f('ix_stock_calculations_kode_plant'), table_name='stock_calculations')
    op.drop_index(op.f('ix_stock_calculations_id'), table_name='stock_calculations')
    op.drop_table('stock_calculations')
    op.drop_index('ix_sap_stock_tanggal_plant_jenis', table_name='sap_stock')
    op.drop_index(op.f('ix_sap_stock_tanggal'), table_name='sap_stock')
    op.drop_index(op.f('ix_sap_stock_kode_plant'), table_name='sap_stock')
    op.drop_index(op.f('ix_sap_stock_id'), table_name='sap_stock')
    op.drop_table('sap_stock')
    op.drop_index(op.f('ix_sap_outstanding_do_tanggal'), table_name='sap_outstanding_do')
    op.drop_index(op.f('ix_sap_outstanding_do_kode_plant'), table_name='sap_outstanding_do')
    op.drop_index(op.f('ix_sap_outstanding_do_id'), table_name='sap_outstanding_do')
    op.drop_index('ix_sap_do_tanggal_plant_jenis', table_name='sap_outstanding_do')
    op.drop_table('sap_outstanding_do')
    op.drop_index(op.f('ix_safety_stock_kode_kab'), table_name='safety_stock')
    op.drop_index(op.f('ix_safety_stock_id'), table_name='safety_stock')
    op.drop_table('safety_stock')
    op.drop_index('ix_photos_tanggal_plant', table_name='photos')
    op.drop_index(op.f('ix_photos_tanggal'), table_name='photos')
    op.drop_index(op.f('ix_photos_kode_plant'), table_name='photos')
    op.drop_index(op.f('ix_photos_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_notification_log_id'), table_name='notification_log')
    op.drop_table('notification_log')
    op.drop_index(op.f('ix_master_plant_kode_plant'), table_name='master_plant')
    op.drop_index(op.f('ix_master_plant_kode_kab'), table_name='master_plant')
    op.drop_index(op.f('ix_master_plant_id'), table_name='master_plant')
    op.drop_table('master_plant')
    # ### end Alembic commands ###
